### ISSUE TITLE
[FR] Project Examples for PlatformIO Registry

### ISSUE THREAD

**Issue by Sean0203** [Viethas-Firmware/VhJson#1]
Hi,

Currently, the [library page](https://registry.platformio.org/libraries/redhat2410/VhJson) in the PlatformIO Registry doesn't contain any quick start projects for developers. Such examples serve both to highlight widespread use cases and to help newcomers to get up and running much more quickly.

Please consider adding a few comprehensive project examples to the PlatformIO Registry.

Useful links:
- https://registry.platformio.org/libraries/redhat2410/VhJson
- https://docs.platformio.org/en/latest/manifests/library-json/fields/examples.html

**Comment by redhat2410** [comment]
Hi,
I appreciate your feedback, and in version 1.1.2 I have updated the examples and libraries. Please let me know if there are any mistakes so that I can continue to enhance the library. I will close this issue. Thank you.
